### ISSUE TITLE
PUBLIC_PORT

### ISSUE THREAD

**Issue by Laurentmichel4irulez** [mplx/docker-webvirtcloud#4]
I tried to use the PUBLIC_PORT env property to change to port from 80 to 8080. 
But the login page is still on the port 80.

**Comment by mplx** [comment]
`PUBLIC_PORT` is not for running the webserver on another port but to fix the http redirects of webvirtcloud *in case you use another port* (host:container port mapping).

To run on another port you need to change the host:container port mapping, which depends on your actual setup, ie. if you use a proxy or not, use docker cli directly, compose, swarm, etc.

See https://docs.docker.com/engine/reference/run/#expose-incoming-ports

Example for running the webvirtcloud container on `8080` with `docker run`:
```
docker run -d \
    -p 8080:80 \
    -e PUBLIC_PORT=8080 \
    -v /srv/webvirtcloud/data:/srv/webvirtcloud/data \
    -v /srv/webvirtcloud/ssh:/var/www/.ssh \
    --name webvirtcloud \
    mplx/docker-webvirtcloud:latest
```
Notice the parameters `-p 8080:80` and `-e PUBLIC_PORT=8080`

**Comment by Laurentmichel4irulez** [comment]
Hi,



I saw the documentation but even with -p 8080:80 and -e PUBLIC_PORT=8080 the login page is redirected to the default port 80. 



I executed the exact docker command you provided.



Kr,
Laurent


Op 17 okt 2018 om 18:38 uur uur schreef mplx <notifications@github.com>:



PUBLIC_PORT is not for running the webserver on another port but to fix the http redirects of webvirtcloud in case you use another port (host:container port mapping).

To run on another port you need to change the host:container port mapping, which depends on your actual setup, ie. if you use a proxy or not, use docker cli directly, compose, swarm, etc.

See https://docs.docker.com/engine/reference/run/#expose-incoming-ports


Example for running the webvirtcloud container on 8080 with docker run:

docker run -d \
    -p 8080:80 \
    -e PUBLIC_PORT=8080 \
    -v /srv/webvirtcloud/data:/srv/webvirtcloud/data \
    -v /srv/webvirtcloud/ssh:/var/www/.ssh \
    --name webvirtcloud \
    mplx/docker-webvirtcloud:latest


Notice the parameters -p 8080:80 and -e PUBLIC_PORT=8080

**Comment by mplx** [comment]
Pull the latest image and use a `-p 8080:8080` mapping (and `PUBLIC_PORT=8080`).

```
curl -L localhost:8080

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="WebVirtMgr panel for manage virtual machine">
    <meta name="author" content="anatoliy.guskov@gmail.com">

    <title>WebVirtCloud - Sign In</title>
...
```

**Comment by Laurentmichel4irulez** [comment]
This is indeed working now on port 8080 thanks.

But it looks like you change introduced an other issue.

When I now open a Instance I get:

Oops!

500 Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete you request.




The VNC to the Virtual machine is working.

**Comment by Intellium** [comment]
Try logging in with another (super) user, besides the default admin account. I had this same issue and this made it go away.

**Comment by mplx** [comment]
We tested the update before tagging it with our few installations and didn't encouter any problems (usually we try be most conservative with updates; we run our internal master tree and tag it weeks after to keep it most stable). However - no default admin. I guess this might be a problem with the upgrade path of webvirtcloud - has there been something usefull in the logs?

**Comment by prueg3l** [comment]
After installation, user admin is not configured as it should be. Just go to "Users" and enter the missing configuration parameters. After completion, everything works fine.
