### ISSUE TITLE
Does not work through an external proxy

### ISSUE THREAD

**Issue by Aphris-Karu** [mplx/docker-webvirtcloud#6]
I've been trying to get it to work with HAProxy as the external proxy. The issue comes in setting the WS_PUBLIC_HOST variable in the settings.py file.

Your init sets the WS_PUBLIC_PORT from VNC_PORT variable but does not set the host.
You should add the following to set the host 

```
echo "Setting VNC External Host..."
if [ -n "$VNC_HOST" ]; then
	sed -i "s/WS_PUBLIC_HOST = None/WS_PUBLIC_HOST = $VNC_HOST/" /srv/webvirtcloud/webvirtcloud/settings.py
fi
```

The above code has been tested but you have to put quotes around the host name to get it to work correctly.

**Comment by mplx** [comment]
Thanks for your fix! I've integrated in the master branch.

Can you please verify if the docker-webvirtcloud:master image works for you so I can tag it as stable?
